<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="0"
            tests="0">

  <testsuite name="NightWatchTests"
    errors="0" failures="0" hostname="" id="" package="NightWatchTests" skipped="6"
    tests="0" time="0" timestamp="">
  

  
    <system-err>
        Error: An error occurred while retrieving a new session: &#34;Connection refused to 127.0.0.1:9514&#34;. If the Webdriver/Selenium service is managed by Nightwatch, check if &#34;start_process&#34; is set to &#34;true&#34;.
       at emitErrorNT (internal/streams/destroy.js:106:8)
       at emitErrorCloseNT (internal/streams/destroy.js:74:3)
       at processTicksAndRejections (internal/process/task_queues.js:82:21)
    </system-err>
  

    
    <error message="An error occurred while retrieving a new session: &#34;Connection refused to 127.0.0.1:9514&#34;. If the Webdriver/Selenium service is managed by Nightwatch, check if &#34;start_process&#34; is set to &#34;true&#34;."><![CDATA[
      Error: An error occurred while retrieving a new session: &#34;Connection refused to 127.0.0.1:9514&#34;. If the Webdriver/Selenium service is managed by Nightwatch, check if &#34;start_process&#34; is set to &#34;true&#34;.
    at JsonWireProtocol.handleSessionCreateError (C:\Users\micha\OneDrive\Pulpit\vue\Vue Home App\home-application-for-flatmates\home-app\test_NightWatch\node_modules\nightwatch\lib\transport\transport.js:110:15)
    at HttpRequest.&lt;anonymous&gt; (C:\Users\micha\OneDrive\Pulpit\vue\Vue Home App\home-application-for-flatmates\home-app\test_NightWatch\node_modules\nightwatch\lib\transport\transport.js:166:32)
    at HttpRequest.emit (events.js:375:28)
    at ClientRequest.&lt;anonymous&gt; (C:\Users\micha\OneDrive\Pulpit\vue\Vue Home App\home-application-for-flatmates\home-app\test_NightWatch\node_modules\nightwatch\lib\http\request.js:143:19)
    at ClientRequest.emit (events.js:387:35)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:375:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
      ]]></error>  

  
    
    <testcase
      name="Log in and go to product panel" classname="NightWatchTests">
      <skipped />
    </testcase>
    
    <testcase
      name="Add items to Product panel" classname="NightWatchTests">
      <skipped />
    </testcase>
    
    <testcase
      name="Delete items from Product panel" classname="NightWatchTests">
      <skipped />
    </testcase>
    
    <testcase
      name="Go to Split panel and add some bills" classname="NightWatchTests">
      <skipped />
    </testcase>
    
    <testcase
      name="Go to Cleaning panel and add some duties" classname="NightWatchTests">
      <skipped />
    </testcase>
    
    <testcase
      name="Log out" classname="NightWatchTests">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
